### ISSUE TITLE
Section 6: Apply the loop transformation

### ISSUE THREAD

**Issue by bwh10** [HPCE/hpce_2014_cw3#4]
In this section, it states: "Apply the loop transformation described above, without introducing any parallelism, and check it works with various values of K, via the environment variable HPCE_FFT_LOOP_K." 

It is quite ambiguous in what it means by "without introducing any parallelism". From what I understand, we should implement a chunked parfor loop for the FFT without using parallel task groups for this task?

Hope this can be clarified more clearly. Thanks!

**Comment by m8pple** [comment]
Thanks for filing the issue. The idea is that you should:
1. Apply the chunking in a sequential loop, to make sure it still gives the right result.
2. Once the loop is correct, convert it to a chunked parallel loop using simple_partitioner.

The idea is that people think the parallelism is what makes it complex to do, but actually
most people encounter problems with the loop transform and just _think_ it is due to
parallelism :)

Anyway, thanks for pointing it out, it was wrong as written.
